local TDSHub = Instance.new("ScreenGui")
TDSHub.Name = "TDSHub"
TDSHub.ResetOnSpawn = false
TDSHub.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
TDSHub.DisplayOrder = 100
TDSHub.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")

local Executor = Instance.new("Frame")
Executor.Name = "Executor"
Executor.Position = UDim2.new(0.5, 0, 0.5, 0)
Executor.Size = UDim2.new(0, 300, 0, 350)
Executor.BackgroundColor3 = Color3.new(0.109804, 0.0745098, 0.133333)
Executor.BorderSizePixel = 0
Executor.BorderColor3 = Color3.new(0, 0, 0)
Executor.ZIndex = 99
Executor.AnchorPoint = Vector2.new(0.5, 0.5)
Executor.Parent = TDSHub

local UIDragDetector = Instance.new("UIDragDetector")
UIDragDetector.Name = "UIDragDetector"

UIDragDetector.Parent = Executor

local Title = Instance.new("TextLabel")
Title.Name = "Title"
Title.Position = UDim2.new(0.02, 0, 0.00571429, 0)
Title.Size = UDim2.new(0, 200, 0, 50)
Title.BackgroundColor3 = Color3.new(1, 1, 1)
Title.BackgroundTransparency = 1
Title.BorderSizePixel = 0
Title.BorderColor3 = Color3.new(0, 0, 0)
Title.Transparency = 1
Title.Text = "Program Executor"
Title.TextColor3 = Color3.new(1, 0, 1)
Title.TextSize = 14
Title.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Title.TextScaled = true
Title.TextWrapped = true
Title.TextXAlignment = Enum.TextXAlignment.Left
Title.Parent = Executor

local LineX = Instance.new("Frame")
LineX.Name = "LineX"
LineX.Size = UDim2.new(1, 0, 0.007, 0)
LineX.BackgroundColor3 = Color3.new(1, 0, 1)
LineX.BorderSizePixel = 0
LineX.BorderColor3 = Color3.new(0, 0, 0)
LineX.Parent = Executor

local ExecutorButton = Instance.new("TextButton")
ExecutorButton.Name = "ExecutorButton"
ExecutorButton.Position = UDim2.new(0.03, 0, 0.85, 0)
ExecutorButton.Size = UDim2.new(0, 150, 0, 45)
ExecutorButton.BackgroundColor3 = Color3.new(0.294118, 0, 0.588235)
ExecutorButton.BorderSizePixel = 0
ExecutorButton.BorderColor3 = Color3.new(0, 0, 0)
ExecutorButton.Text = ""
ExecutorButton.TextColor3 = Color3.new(1, 1, 1)
ExecutorButton.TextSize = 14
ExecutorButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
ExecutorButton.TextWrapped = true
ExecutorButton.TextXAlignment = Enum.TextXAlignment.Right
ExecutorButton.Parent = Executor

local UICorner = Instance.new("UICorner")
UICorner.Name = "UICorner"
UICorner.CornerRadius = UDim.new(0.2, 0)
UICorner.Parent = ExecutorButton

local IconPlay = Instance.new("ImageLabel")
IconPlay.Name = "IconPlay"
IconPlay.Position = UDim2.new(0.2, 0, 0.5, 0)
IconPlay.Size = UDim2.new(0.75, 0, 0.75, 0)
IconPlay.BackgroundColor3 = Color3.new(1, 1, 1)
IconPlay.BackgroundTransparency = 1
IconPlay.BorderSizePixel = 0
IconPlay.BorderColor3 = Color3.new(0, 0, 0)
IconPlay.AnchorPoint = Vector2.new(0.5, 0.5)
IconPlay.Transparency = 1
IconPlay.Image = "rbxassetid://8517323790"
IconPlay.ImageColor3 = Color3.new(1, 0, 0.686275)
IconPlay.Parent = ExecutorButton

local UIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
UIAspectRatioConstraint.Name = "UIAspectRatioConstraint"

UIAspectRatioConstraint.Parent = IconPlay

local IconStop = Instance.new("ImageLabel")
IconStop.Name = "IconStop"
IconStop.Size = UDim2.new(1, 0, 1, 0)
IconStop.BackgroundColor3 = Color3.new(1, 1, 1)
IconStop.BackgroundTransparency = 1
IconStop.BorderSizePixel = 0
IconStop.BorderColor3 = Color3.new(0, 0, 0)
IconStop.Visible = false
IconStop.Transparency = 1
IconStop.Image = "rbxassetid://94079325461679"
IconStop.ImageColor3 = Color3.new(1, 0, 0.686275)
IconStop.Parent = ExecutorButton

local UIAspectRatioConstraint2 = Instance.new("UIAspectRatioConstraint")
UIAspectRatioConstraint2.Name = "UIAspectRatioConstraint"

UIAspectRatioConstraint2.Parent = IconStop

local TextStatusButton = Instance.new("TextLabel")
TextStatusButton.Name = "TextStatusButton"
TextStatusButton.Position = UDim2.new(0.1, 0, 0, 0)
TextStatusButton.Size = UDim2.new(1, 0, 1, 0)
TextStatusButton.BackgroundColor3 = Color3.new(1, 1, 1)
TextStatusButton.BackgroundTransparency = 1
TextStatusButton.BorderSizePixel = 0
TextStatusButton.BorderColor3 = Color3.new(0, 0, 0)
TextStatusButton.Transparency = 1
TextStatusButton.Text = "Play"
TextStatusButton.TextColor3 = Color3.new(1, 1, 1)
TextStatusButton.TextSize = 25
TextStatusButton.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TextStatusButton.TextWrapped = true
TextStatusButton.Parent = ExecutorButton

local UIStroke = Instance.new("UIStroke")
UIStroke.Name = "UIStroke"
UIStroke.Color = Color3.new(1, 0, 1)
UIStroke.Thickness = 2
UIStroke.Transparency = 1
UIStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke.Parent = ExecutorButton

local ShadowFrame = Instance.new("Frame")
ShadowFrame.Name = "ShadowFrame"
ShadowFrame.Size = UDim2.new(1, 0, 1, 0)
ShadowFrame.BackgroundColor3 = Color3.new(0, 0, 0)
ShadowFrame.BackgroundTransparency = 1
ShadowFrame.BorderSizePixel = 0
ShadowFrame.BorderColor3 = Color3.new(0, 0, 0)
ShadowFrame.Transparency = 1
ShadowFrame.Parent = ExecutorButton

local UICorner2 = Instance.new("UICorner")
UICorner2.Name = "UICorner"
UICorner2.CornerRadius = UDim.new(0.2, 0)
UICorner2.Parent = ShadowFrame

local LineY = Instance.new("Frame")
LineY.Name = "LineY"
LineY.Size = UDim2.new(0.007, 0, 1, 0)
LineY.BackgroundColor3 = Color3.new(1, 0, 1)
LineY.BorderSizePixel = 0
LineY.BorderColor3 = Color3.new(0, 0, 0)
LineY.Parent = Executor

local ConsoleScrolling = Instance.new("ScrollingFrame")
ConsoleScrolling.Name = "ConsoleScrolling"
ConsoleScrolling.Position = UDim2.new(0.5, 0, 0.4, 0)
ConsoleScrolling.Size = UDim2.new(0.95, 0, 0.45, 0)
ConsoleScrolling.BackgroundColor3 = Color3.new(0.0627451, 0.0588235, 0.0705882)
ConsoleScrolling.BorderSizePixel = 0
ConsoleScrolling.BorderColor3 = Color3.new(0, 0, 0)
ConsoleScrolling.AnchorPoint = Vector2.new(0.5, 0.5)
ConsoleScrolling.Active = true
ConsoleScrolling.CanvasSize = UDim2.new(0, 0, 0, 0)
ConsoleScrolling.ScrollBarImageColor3 = Color3.new(1, 0, 1)
ConsoleScrolling.ScrollBarImageTransparency = 0.75
ConsoleScrolling.ScrollBarThickness = 5
ConsoleScrolling.AutomaticCanvasSize = Enum.AutomaticSize.Y
ConsoleScrolling.Parent = Executor

local UIStroke2 = Instance.new("UIStroke")
UIStroke2.Name = "UIStroke"
UIStroke2.Color = Color3.new(0.462745, 0, 0.462745)
UIStroke2.Transparency = 0.5
UIStroke2.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke2.Parent = ConsoleScrolling

local OutputSample = Instance.new("TextLabel")
OutputSample.Name = "OutputSample"
OutputSample.Position = UDim2.new(0.025, 0, 0, 0)
OutputSample.Size = UDim2.new(0.95, 0, 0, 20)
OutputSample.BackgroundColor3 = Color3.new(1, 1, 1)
OutputSample.BackgroundTransparency = 1
OutputSample.BorderSizePixel = 0
OutputSample.BorderColor3 = Color3.new(0, 0, 0)
OutputSample.Visible = false
OutputSample.Transparency = 1
OutputSample.Text = "[System]: 1m1m1m1m1m1m1m1m1m1m1m"
OutputSample.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
OutputSample.TextSize = 17
OutputSample.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
OutputSample.TextXAlignment = Enum.TextXAlignment.Left
OutputSample.Parent = ConsoleScrolling

local ResetButton = Instance.new("TextButton")
ResetButton.Name = "ResetButton"
ResetButton.Position = UDim2.new(0.57, 0, 0.85, 0)
ResetButton.Size = UDim2.new(0, 120, 0, 45)
ResetButton.BackgroundColor3 = Color3.new(0.294118, 0, 0.588235)
ResetButton.BorderSizePixel = 0
ResetButton.BorderColor3 = Color3.new(0, 0, 0)
ResetButton.Text = ""
ResetButton.TextColor3 = Color3.new(1, 1, 1)
ResetButton.TextSize = 14
ResetButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
ResetButton.TextWrapped = true
ResetButton.TextXAlignment = Enum.TextXAlignment.Right
ResetButton.Parent = Executor

local UICorner3 = Instance.new("UICorner")
UICorner3.Name = "UICorner"
UICorner3.CornerRadius = UDim.new(0.2, 0)
UICorner3.Parent = ResetButton

local IconReset = Instance.new("ImageLabel")
IconReset.Name = "IconReset"
IconReset.Position = UDim2.new(0.2, 0, 0.5, 0)
IconReset.Size = UDim2.new(0.725, 0, 0.725, 0)
IconReset.BackgroundColor3 = Color3.new(1, 1, 1)
IconReset.BackgroundTransparency = 1
IconReset.BorderSizePixel = 0
IconReset.BorderColor3 = Color3.new(0, 0, 0)
IconReset.AnchorPoint = Vector2.new(0.5, 0.5)
IconReset.Transparency = 1
IconReset.Image = "rbxassetid://6723921202"
IconReset.ImageColor3 = Color3.new(1, 0, 0.686275)
IconReset.Parent = ResetButton

local UIAspectRatioConstraint3 = Instance.new("UIAspectRatioConstraint")
UIAspectRatioConstraint3.Name = "UIAspectRatioConstraint"

UIAspectRatioConstraint3.Parent = IconReset

local TextStatusButton2 = Instance.new("TextLabel")
TextStatusButton2.Name = "TextStatusButton"
TextStatusButton2.Position = UDim2.new(0.15, 0, 0, 0)
TextStatusButton2.Size = UDim2.new(1, 0, 1, 0)
TextStatusButton2.BackgroundColor3 = Color3.new(1, 1, 1)
TextStatusButton2.BackgroundTransparency = 1
TextStatusButton2.BorderSizePixel = 0
TextStatusButton2.BorderColor3 = Color3.new(0, 0, 0)
TextStatusButton2.Transparency = 1
TextStatusButton2.Text = "Reset"
TextStatusButton2.TextColor3 = Color3.new(1, 1, 1)
TextStatusButton2.TextSize = 25
TextStatusButton2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TextStatusButton2.TextWrapped = true
TextStatusButton2.Parent = ResetButton

local UIStroke3 = Instance.new("UIStroke")
UIStroke3.Name = "UIStroke"
UIStroke3.Color = Color3.new(1, 0, 1)
UIStroke3.Thickness = 2
UIStroke3.Transparency = 1
UIStroke3.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke3.Parent = ResetButton

local ShadowFrame2 = Instance.new("Frame")
ShadowFrame2.Name = "ShadowFrame"
ShadowFrame2.Size = UDim2.new(1, 0, 1, 0)
ShadowFrame2.BackgroundColor3 = Color3.new(0, 0, 0)
ShadowFrame2.BackgroundTransparency = 1
ShadowFrame2.BorderSizePixel = 0
ShadowFrame2.BorderColor3 = Color3.new(0, 0, 0)
ShadowFrame2.Transparency = 1
ShadowFrame2.Parent = ResetButton

local UICorner4 = Instance.new("UICorner")
UICorner4.Name = "UICorner"
UICorner4.CornerRadius = UDim.new(0.2, 0)
UICorner4.Parent = ShadowFrame2

local CloseButton = Instance.new("ImageButton")
CloseButton.Name = "CloseButton"
CloseButton.Position = UDim2.new(0.86, 0, 0.025, 0)
CloseButton.Size = UDim2.new(0, 35, 0, 35)
CloseButton.BackgroundColor3 = Color3.new(1, 0, 0.588235)
CloseButton.BorderSizePixel = 0
CloseButton.BorderColor3 = Color3.new(0, 0, 0)
CloseButton.Image = "rbxassetid://14203224837"
CloseButton.Parent = Executor

local UIAspectRatioConstraint4 = Instance.new("UIAspectRatioConstraint")
UIAspectRatioConstraint4.Name = "UIAspectRatioConstraint"

UIAspectRatioConstraint4.Parent = CloseButton

local UICorner5 = Instance.new("UICorner")
UICorner5.Name = "UICorner"
UICorner5.CornerRadius = UDim.new(0.15, 0)
UICorner5.Parent = CloseButton

local MinimizeButton = Instance.new("ImageButton")
MinimizeButton.Name = "MinimizeButton"
MinimizeButton.Position = UDim2.new(0.725, 0, 0.025, 0)
MinimizeButton.Size = UDim2.new(0, 35, 0, 35)
MinimizeButton.BackgroundColor3 = Color3.new(1, 0, 0.588235)
MinimizeButton.BorderSizePixel = 0
MinimizeButton.BorderColor3 = Color3.new(0, 0, 0)
MinimizeButton.Parent = Executor

local UIAspectRatioConstraint5 = Instance.new("UIAspectRatioConstraint")
UIAspectRatioConstraint5.Name = "UIAspectRatioConstraint"

UIAspectRatioConstraint5.Parent = MinimizeButton

local UICorner6 = Instance.new("UICorner")
UICorner6.Name = "UICorner"
UICorner6.CornerRadius = UDim.new(0.15, 0)
UICorner6.Parent = MinimizeButton

local MiniIcon = Instance.new("TextLabel")
MiniIcon.Name = "MiniIcon"
MiniIcon.Position = UDim2.new(0.47, 0, 0.325, 0)
MiniIcon.Size = UDim2.new(1, 0, 1, 0)
MiniIcon.BackgroundColor3 = Color3.new(1, 1, 1)
MiniIcon.BackgroundTransparency = 1
MiniIcon.BorderSizePixel = 0
MiniIcon.BorderColor3 = Color3.new(0, 0, 0)
MiniIcon.AnchorPoint = Vector2.new(0.5, 0.5)
MiniIcon.Transparency = 1
MiniIcon.Text = "-"
MiniIcon.TextColor3 = Color3.new(1, 1, 1)
MiniIcon.TextSize = 70
MiniIcon.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
MiniIcon.TextWrapped = true
MiniIcon.Parent = MinimizeButton

local ZoomIcon = Instance.new("TextLabel")
ZoomIcon.Name = "ZoomIcon"
ZoomIcon.Position = UDim2.new(0.475, 0, 0.425, 0)
ZoomIcon.Size = UDim2.new(1, 0, 1, 0)
ZoomIcon.BackgroundColor3 = Color3.new(1, 1, 1)
ZoomIcon.BackgroundTransparency = 1
ZoomIcon.BorderSizePixel = 0
ZoomIcon.BorderColor3 = Color3.new(0, 0, 0)
ZoomIcon.Visible = false
ZoomIcon.AnchorPoint = Vector2.new(0.5, 0.5)
ZoomIcon.Transparency = 1
ZoomIcon.Text = "+"
ZoomIcon.TextColor3 = Color3.new(1, 1, 1)
ZoomIcon.TextSize = 50
ZoomIcon.FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
ZoomIcon.TextWrapped = true
ZoomIcon.Parent = MinimizeButton

local ManageProgramButton = Instance.new("TextButton")
ManageProgramButton.Name = "ManageProgramButton"
ManageProgramButton.Position = UDim2.new(0.5, 0, 0.7, 0)
ManageProgramButton.Size = UDim2.new(0, 275, 0, 45)
ManageProgramButton.BackgroundColor3 = Color3.new(0.560784, 0, 0.713726)
ManageProgramButton.BorderSizePixel = 0
ManageProgramButton.BorderColor3 = Color3.new(0, 0, 0)
ManageProgramButton.AnchorPoint = Vector2.new(0.5, 0)
ManageProgramButton.Text = ""
ManageProgramButton.TextColor3 = Color3.new(1, 1, 1)
ManageProgramButton.TextSize = 14
ManageProgramButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
ManageProgramButton.TextWrapped = true
ManageProgramButton.TextXAlignment = Enum.TextXAlignment.Right
ManageProgramButton.Parent = Executor

local UICorner7 = Instance.new("UICorner")
UICorner7.Name = "UICorner"
UICorner7.CornerRadius = UDim.new(0.2, 0)
UICorner7.Parent = ManageProgramButton

local IconLoad = Instance.new("ImageLabel")
IconLoad.Name = "IconLoad"
IconLoad.Position = UDim2.new(0.125, 0, 0.5, 0)
IconLoad.Size = UDim2.new(0.9, 0, 0.9, 0)
IconLoad.BackgroundColor3 = Color3.new(1, 1, 1)
IconLoad.BackgroundTransparency = 1
IconLoad.BorderSizePixel = 0
IconLoad.BorderColor3 = Color3.new(0, 0, 0)
IconLoad.AnchorPoint = Vector2.new(0.5, 0.5)
IconLoad.Transparency = 1
IconLoad.Image = "rbxassetid://8456591132"
IconLoad.ImageColor3 = Color3.new(1, 0, 0.686275)
IconLoad.Parent = ManageProgramButton

local UIAspectRatioConstraint6 = Instance.new("UIAspectRatioConstraint")
UIAspectRatioConstraint6.Name = "UIAspectRatioConstraint"

UIAspectRatioConstraint6.Parent = IconLoad

local TextStatusButton3 = Instance.new("TextLabel")
TextStatusButton3.Name = "TextStatusButton"
TextStatusButton3.Position = UDim2.new(0.575, 0, 0.5, 0)
TextStatusButton3.Size = UDim2.new(1, 0, 1, 0)
TextStatusButton3.BackgroundColor3 = Color3.new(1, 1, 1)
TextStatusButton3.BackgroundTransparency = 1
TextStatusButton3.BorderSizePixel = 0
TextStatusButton3.BorderColor3 = Color3.new(0, 0, 0)
TextStatusButton3.AnchorPoint = Vector2.new(0.5, 0.5)
TextStatusButton3.Transparency = 1
TextStatusButton3.Text = "Manage program"
TextStatusButton3.TextColor3 = Color3.new(1, 1, 1)
TextStatusButton3.TextSize = 23
TextStatusButton3.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TextStatusButton3.TextWrapped = true
TextStatusButton3.Parent = ManageProgramButton

local UIStroke4 = Instance.new("UIStroke")
UIStroke4.Name = "UIStroke"
UIStroke4.Color = Color3.new(1, 0, 1)
UIStroke4.Thickness = 2
UIStroke4.Transparency = 1
UIStroke4.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke4.Parent = ManageProgramButton

local ShadowFrame3 = Instance.new("Frame")
ShadowFrame3.Name = "ShadowFrame"
ShadowFrame3.Size = UDim2.new(1, 0, 1, 0)
ShadowFrame3.BackgroundColor3 = Color3.new(0, 0, 0)
ShadowFrame3.BackgroundTransparency = 1
ShadowFrame3.BorderSizePixel = 0
ShadowFrame3.BorderColor3 = Color3.new(0, 0, 0)
ShadowFrame3.Transparency = 1
ShadowFrame3.Parent = ManageProgramButton

local UICorner8 = Instance.new("UICorner")
UICorner8.Name = "UICorner"
UICorner8.CornerRadius = UDim.new(0.2, 0)
UICorner8.Parent = ShadowFrame3

local ManageProgramFrame = Instance.new("Frame")
ManageProgramFrame.Name = "ManageProgramFrame"
ManageProgramFrame.Position = UDim2.new(0.5, 0, 0.5, 0)
ManageProgramFrame.Size = UDim2.new(0, 350, 0, 200)
ManageProgramFrame.BackgroundColor3 = Color3.new(0.109804, 0.0745098, 0.133333)
ManageProgramFrame.BorderSizePixel = 0
ManageProgramFrame.BorderColor3 = Color3.new(0, 0, 0)
ManageProgramFrame.Visible = false
ManageProgramFrame.ZIndex = 100
ManageProgramFrame.AnchorPoint = Vector2.new(0.5, 0.5)
ManageProgramFrame.Parent = TDSHub

local LineX2 = Instance.new("Frame")
LineX2.Name = "LineX"
LineX2.Position = UDim2.new(0.5, 0, 1, 0)
LineX2.Size = UDim2.new(1, 0, 0.01, 0)
LineX2.BackgroundColor3 = Color3.new(1, 0, 1)
LineX2.BorderSizePixel = 0
LineX2.BorderColor3 = Color3.new(0, 0, 0)
LineX2.AnchorPoint = Vector2.new(0.5, 0.5)
LineX2.Parent = ManageProgramFrame

local LineY2 = Instance.new("Frame")
LineY2.Name = "LineY"
LineY2.Position = UDim2.new(1, 0, 0.5, 0)
LineY2.Size = UDim2.new(0.01, 0, 1, 0)
LineY2.BackgroundColor3 = Color3.new(1, 0, 1)
LineY2.BorderSizePixel = 0
LineY2.BorderColor3 = Color3.new(0, 0, 0)
LineY2.AnchorPoint = Vector2.new(0.5, 0.5)
LineY2.Parent = ManageProgramFrame

local Title2 = Instance.new("TextLabel")
Title2.Name = "Title"
Title2.Position = UDim2.new(0.02, 0, 0.00571429, 0)
Title2.Size = UDim2.new(0, 150, 0, 40)
Title2.BackgroundColor3 = Color3.new(1, 1, 1)
Title2.BackgroundTransparency = 1
Title2.BorderSizePixel = 0
Title2.BorderColor3 = Color3.new(0, 0, 0)
Title2.Transparency = 1
Title2.Text = "Program manage"
Title2.TextColor3 = Color3.new(1, 0, 1)
Title2.TextSize = 20
Title2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Title2.TextScaled = true
Title2.TextWrapped = true
Title2.TextXAlignment = Enum.TextXAlignment.Left
Title2.Parent = ManageProgramFrame

local ComeBackButton = Instance.new("ImageButton")
ComeBackButton.Name = "ComeBackButton"
ComeBackButton.Position = UDim2.new(0.875, 0, 0.025, 0)
ComeBackButton.Size = UDim2.new(0, 35, 0, 35)
ComeBackButton.BackgroundColor3 = Color3.new(1, 0, 0.588235)
ComeBackButton.BorderSizePixel = 0
ComeBackButton.BorderColor3 = Color3.new(0, 0, 0)
ComeBackButton.Image = "rbxassetid://111290129018455"
ComeBackButton.Parent = ManageProgramFrame

local UIAspectRatioConstraint7 = Instance.new("UIAspectRatioConstraint")
UIAspectRatioConstraint7.Name = "UIAspectRatioConstraint"

UIAspectRatioConstraint7.Parent = ComeBackButton

local UICorner9 = Instance.new("UICorner")
UICorner9.Name = "UICorner"
UICorner9.CornerRadius = UDim.new(0.15, 0)
UICorner9.Parent = ComeBackButton

local ProgramBox = Instance.new("TextBox")
ProgramBox.Name = "ProgramBox"
ProgramBox.Position = UDim2.new(0.5, 0, 0.475, 0)
ProgramBox.Size = UDim2.new(0, 325, 0, 95)
ProgramBox.BackgroundColor3 = Color3.new(0.0627451, 0.0588235, 0.0705882)
ProgramBox.BorderSizePixel = 0
ProgramBox.BorderColor3 = Color3.new(0, 0, 0)
ProgramBox.Visible = false
ProgramBox.AnchorPoint = Vector2.new(0.5, 0.5)
ProgramBox.Text = ""
ProgramBox.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
ProgramBox.TextSize = 14
ProgramBox.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
ProgramBox.TextScaled = true
ProgramBox.TextWrapped = true
ProgramBox.TextXAlignment = Enum.TextXAlignment.Left
ProgramBox.TextYAlignment = Enum.TextYAlignment.Top
ProgramBox.PlaceholderText = "Paste your program here..."
ProgramBox.PlaceholderColor3 = Color3.new(0.705882, 0.588235, 0.705882)
ProgramBox.Parent = ManageProgramFrame

local UIStroke5 = Instance.new("UIStroke")
UIStroke5.Name = "UIStroke"
UIStroke5.Color = Color3.new(1, 0, 1)
UIStroke5.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke5.Parent = ProgramBox

local LoadProgramButton = Instance.new("TextButton")
LoadProgramButton.Name = "LoadProgramButton"
LoadProgramButton.Position = UDim2.new(0.5, 0, 0.85, 0)
LoadProgramButton.Size = UDim2.new(0, 200, 0, 40)
LoadProgramButton.BackgroundColor3 = Color3.new(0.784314, 0, 0.784314)
LoadProgramButton.BorderSizePixel = 0
LoadProgramButton.BorderColor3 = Color3.new(0, 0, 0)
LoadProgramButton.Visible = false
LoadProgramButton.AnchorPoint = Vector2.new(0.5, 0.5)
LoadProgramButton.Text = "Load program"
LoadProgramButton.TextColor3 = Color3.new(1, 1, 1)
LoadProgramButton.TextSize = 20
LoadProgramButton.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
LoadProgramButton.TextWrapped = true
LoadProgramButton.Parent = ManageProgramFrame

local UICorner10 = Instance.new("UICorner")
UICorner10.Name = "UICorner"
UICorner10.CornerRadius = UDim.new(0.15, 0)
UICorner10.Parent = LoadProgramButton

local ShadowFrame4 = Instance.new("Frame")
ShadowFrame4.Name = "ShadowFrame"
ShadowFrame4.Size = UDim2.new(1, 0, 1, 0)
ShadowFrame4.BackgroundColor3 = Color3.new(0, 0, 0)
ShadowFrame4.BackgroundTransparency = 1
ShadowFrame4.BorderSizePixel = 0
ShadowFrame4.BorderColor3 = Color3.new(0, 0, 0)
ShadowFrame4.Transparency = 1
ShadowFrame4.Parent = LoadProgramButton

local UICorner11 = Instance.new("UICorner")
UICorner11.Name = "UICorner"
UICorner11.CornerRadius = UDim.new(0.15, 0)
UICorner11.Parent = ShadowFrame4

local LoadProgramTabButton = Instance.new("TextButton")
LoadProgramTabButton.Name = "LoadProgramTabButton"
LoadProgramTabButton.Position = UDim2.new(0, 250, -0.175, 0)
LoadProgramTabButton.Size = UDim2.new(0, 100, 0, 35)
LoadProgramTabButton.BackgroundColor3 = Color3.new(0.109804, 0.0745098, 0.133333)
LoadProgramTabButton.BorderSizePixel = 0
LoadProgramTabButton.BorderColor3 = Color3.new(0, 0, 0)
LoadProgramTabButton.Text = "Load program"
LoadProgramTabButton.TextColor3 = Color3.new(1, 1, 1)
LoadProgramTabButton.TextSize = 14
LoadProgramTabButton.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
LoadProgramTabButton.TextScaled = true
LoadProgramTabButton.TextWrapped = true
LoadProgramTabButton.Parent = ManageProgramFrame

local UIStroke6 = Instance.new("UIStroke")
UIStroke6.Name = "UIStroke"
UIStroke6.Color = Color3.new(1, 0, 0.784314)
UIStroke6.Thickness = 2
UIStroke6.Transparency = 0.25
UIStroke6.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke6.Parent = LoadProgramTabButton

local CustomProgramTabButton = Instance.new("TextButton")
CustomProgramTabButton.Name = "CustomProgramTabButton"
CustomProgramTabButton.Position = UDim2.new(0, 148, -0.175, 0)
CustomProgramTabButton.Size = UDim2.new(0, 100, 0, 35)
CustomProgramTabButton.BackgroundColor3 = Color3.new(0.109804, 0.0745098, 0.133333)
CustomProgramTabButton.BorderSizePixel = 0
CustomProgramTabButton.BorderColor3 = Color3.new(0, 0, 0)
CustomProgramTabButton.Text = "Custom program"
CustomProgramTabButton.TextColor3 = Color3.new(1, 1, 1)
CustomProgramTabButton.TextSize = 14
CustomProgramTabButton.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
CustomProgramTabButton.TextScaled = true
CustomProgramTabButton.TextWrapped = true
CustomProgramTabButton.Parent = ManageProgramFrame

local UIStroke7 = Instance.new("UIStroke")
UIStroke7.Name = "UIStroke"
UIStroke7.Color = Color3.new(1, 0, 0.784314)
UIStroke7.Thickness = 2
UIStroke7.Transparency = 0.25
UIStroke7.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke7.Parent = CustomProgramTabButton

local CustomProgramUI = Instance.new("Folder")
CustomProgramUI.Name = "CustomProgramUI"

CustomProgramUI.Parent = ManageProgramFrame

local MoveProgram = Instance.new("TextButton")
MoveProgram.Name = "MoveProgram"
MoveProgram.Position = UDim2.new(-0.085, 0, 0.6, 0)
MoveProgram.Size = UDim2.new(0, 30, 0, 30)
MoveProgram.BackgroundColor3 = Color3.new(0, 0.490196, 0.815686)
MoveProgram.BorderSizePixel = 0
MoveProgram.BorderColor3 = Color3.new(0, 0, 0)
MoveProgram.ZIndex = 2
MoveProgram.Text = ""
MoveProgram.TextColor3 = Color3.new(1, 1, 1)
MoveProgram.TextSize = 14
MoveProgram.FontFace = Font.new("rbxassetid://12187360881", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
MoveProgram.TextScaled = true
MoveProgram.TextWrapped = true
MoveProgram.Parent = CustomProgramUI

local Icon = Instance.new("ImageLabel")
Icon.Name = "Icon"
Icon.Size = UDim2.new(1, 0, 1, 0)
Icon.BackgroundColor3 = Color3.new(1, 1, 1)
Icon.BackgroundTransparency = 1
Icon.BorderSizePixel = 0
Icon.BorderColor3 = Color3.new(0, 0, 0)
Icon.Transparency = 1
Icon.Image = "rbxassetid://94225529221725"
Icon.Parent = MoveProgram

local UIStroke8 = Instance.new("UIStroke")
UIStroke8.Name = "UIStroke"
UIStroke8.Color = Color3.new(1, 1, 1)
UIStroke8.Thickness = 2
UIStroke8.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke8.Parent = MoveProgram

local DeleteProgram = Instance.new("TextButton")
DeleteProgram.Name = "DeleteProgram"
DeleteProgram.Position = UDim2.new(-0.085, 0, 0.425, 0)
DeleteProgram.Size = UDim2.new(0, 30, 0, 30)
DeleteProgram.BackgroundColor3 = Color3.new(0.854902, 0.235294, 0.235294)
DeleteProgram.BorderSizePixel = 0
DeleteProgram.BorderColor3 = Color3.new(0, 0, 0)
DeleteProgram.ZIndex = 2
DeleteProgram.Text = "-"
DeleteProgram.TextColor3 = Color3.new(1, 1, 1)
DeleteProgram.TextSize = 14
DeleteProgram.FontFace = Font.new("rbxassetid://12187360881", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
DeleteProgram.TextScaled = true
DeleteProgram.TextWrapped = true
DeleteProgram.Parent = CustomProgramUI

local UIStroke9 = Instance.new("UIStroke")
UIStroke9.Name = "UIStroke"
UIStroke9.Color = Color3.new(1, 1, 1)
UIStroke9.Thickness = 2
UIStroke9.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke9.Parent = DeleteProgram

local AddProgram = Instance.new("TextButton")
AddProgram.Name = "AddProgram"
AddProgram.Position = UDim2.new(-0.085, 0, 0.25, 0)
AddProgram.Size = UDim2.new(0, 30, 0, 30)
AddProgram.BackgroundColor3 = Color3.new(0.211765, 0.764706, 0.219608)
AddProgram.BorderSizePixel = 0
AddProgram.BorderColor3 = Color3.new(0, 0, 0)
AddProgram.ZIndex = 2
AddProgram.Text = "+"
AddProgram.TextColor3 = Color3.new(1, 1, 1)
AddProgram.TextSize = 14
AddProgram.FontFace = Font.new("rbxassetid://12187360881", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
AddProgram.TextScaled = true
AddProgram.TextWrapped = true
AddProgram.Parent = CustomProgramUI

local BuildProgramOutput = Instance.new("ScrollingFrame")
BuildProgramOutput.Name = "BuildProgramOutput"
BuildProgramOutput.Position = UDim2.new(0.675, 0, 0.5, 0)
BuildProgramOutput.Size = UDim2.new(0, 200, 0, 100)
BuildProgramOutput.BackgroundColor3 = Color3.new(1, 1, 1)
BuildProgramOutput.BackgroundTransparency = 1
BuildProgramOutput.BorderSizePixel = 0
BuildProgramOutput.BorderColor3 = Color3.new(0, 0, 0)
BuildProgramOutput.AnchorPoint = Vector2.new(0.5, 0.5)
BuildProgramOutput.Transparency = 1
BuildProgramOutput.Active = true
BuildProgramOutput.CanvasSize = UDim2.new(0, 400, 0, 0)
BuildProgramOutput.ScrollBarImageColor3 = Color3.new(0.717647, 0, 1)
BuildProgramOutput.ScrollBarThickness = 4
BuildProgramOutput.AutomaticCanvasSize = Enum.AutomaticSize.XY
BuildProgramOutput.Parent = CustomProgramUI

local OutputSample2 = Instance.new("TextLabel")
OutputSample2.Name = "OutputSample"
OutputSample2.Size = UDim2.new(0, 400, 0, 20)
OutputSample2.BackgroundColor3 = Color3.new(1, 1, 1)
OutputSample2.BackgroundTransparency = 1
OutputSample2.BorderSizePixel = 0
OutputSample2.BorderColor3 = Color3.new(0, 0, 0)
OutputSample2.Transparency = 1
OutputSample2.Text = "Hello work!"
OutputSample2.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
OutputSample2.TextSize = 20
OutputSample2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
OutputSample2.TextWrapped = true
OutputSample2.TextXAlignment = Enum.TextXAlignment.Left
OutputSample2.Parent = BuildProgramOutput

local UIStroke10 = Instance.new("UIStroke")
UIStroke10.Name = "UIStroke"
UIStroke10.Color = Color3.new(1, 0, 1)
UIStroke10.Thickness = 2
UIStroke10.Transparency = 0.5
UIStroke10.Parent = BuildProgramOutput

local BuildProgram = Instance.new("ScrollingFrame")
BuildProgram.Name = "BuildProgram"
BuildProgram.Position = UDim2.new(0.183, 0, 0.625, 0)
BuildProgram.Size = UDim2.new(0, 125, 0, 150)
BuildProgram.BackgroundColor3 = Color3.new(1, 1, 1)
BuildProgram.BackgroundTransparency = 1
BuildProgram.BorderSizePixel = 0
BuildProgram.BorderColor3 = Color3.new(0, 0, 0)
BuildProgram.AnchorPoint = Vector2.new(0.5, 0.5)
BuildProgram.Transparency = 1
BuildProgram.Active = true
BuildProgram.CanvasSize = UDim2.new(0, 0, 0, 0)
BuildProgram.ScrollBarThickness = 4
BuildProgram.AutomaticCanvasSize = Enum.AutomaticSize.Y
BuildProgram.Parent = CustomProgramUI

local UIStroke11 = Instance.new("UIStroke")
UIStroke11.Name = "UIStroke"
UIStroke11.Color = Color3.new(1, 0, 1)
UIStroke11.Thickness = 2
UIStroke11.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke11.Parent = BuildProgram

local ProgramSample = Instance.new("TextButton")
ProgramSample.Name = "ProgramSample"
ProgramSample.Size = UDim2.new(1, 0, 0, 30)
ProgramSample.BackgroundColor3 = Color3.new(0.313726, 0.784314, 0.470588)
ProgramSample.BorderSizePixel = 0
ProgramSample.BorderColor3 = Color3.new(0, 0, 0)
ProgramSample.Text = "#0 - Place"
ProgramSample.TextColor3 = Color3.new(1, 1, 1)
ProgramSample.TextSize = 14
ProgramSample.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
ProgramSample.TextScaled = true
ProgramSample.TextWrapped = true
ProgramSample.Parent = BuildProgram

local UIGradient = Instance.new("UIGradient")
UIGradient.Name = "UIGradient"
UIGradient.Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.new(1, 0.588235, 1)), ColorSequenceKeypoint.new(1, Color3.new(1, 1, 1))})
UIGradient.Parent = ProgramSample

local UICorner12 = Instance.new("UICorner")
UICorner12.Name = "UICorner"
UICorner12.CornerRadius = UDim.new(0.15, 0)
UICorner12.Parent = ProgramSample

local CopyProgramButton = Instance.new("TextButton")
CopyProgramButton.Name = "CopyProgramButton"
CopyProgramButton.Position = UDim2.new(0.83, 0, 0.875, 0)
CopyProgramButton.Size = UDim2.new(0, 100, 0, 40)
CopyProgramButton.BackgroundColor3 = Color3.new(0.784314, 0.294118, 1)
CopyProgramButton.BorderSizePixel = 0
CopyProgramButton.BorderColor3 = Color3.new(0, 0, 0)
CopyProgramButton.AnchorPoint = Vector2.new(0.5, 0.5)
CopyProgramButton.Text = "Copy"
CopyProgramButton.TextColor3 = Color3.new(1, 1, 1)
CopyProgramButton.TextSize = 14
CopyProgramButton.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
CopyProgramButton.TextScaled = true
CopyProgramButton.TextWrapped = true
CopyProgramButton.Parent = CustomProgramUI

local LoadOutputProgramButton = Instance.new("TextButton")
LoadOutputProgramButton.Name = "LoadOutputProgramButton"
LoadOutputProgramButton.Position = UDim2.new(0.525, 0, 0.875, 0)
LoadOutputProgramButton.Size = UDim2.new(0, 100, 0, 40)
LoadOutputProgramButton.BackgroundColor3 = Color3.new(0.392157, 0, 1)
LoadOutputProgramButton.BorderSizePixel = 0
LoadOutputProgramButton.BorderColor3 = Color3.new(0, 0, 0)
LoadOutputProgramButton.AnchorPoint = Vector2.new(0.5, 0.5)
LoadOutputProgramButton.Text = "Load"
LoadOutputProgramButton.TextColor3 = Color3.new(1, 1, 1)
LoadOutputProgramButton.TextSize = 14
LoadOutputProgramButton.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
LoadOutputProgramButton.TextScaled = true
LoadOutputProgramButton.TextWrapped = true
LoadOutputProgramButton.Parent = CustomProgramUI

local ShadowFrame5 = Instance.new("Frame")
ShadowFrame5.Name = "ShadowFrame"
ShadowFrame5.Size = UDim2.new(1, 0, 1, 0)
ShadowFrame5.BackgroundColor3 = Color3.new(0, 0, 0)
ShadowFrame5.BackgroundTransparency = 1
ShadowFrame5.BorderSizePixel = 0
ShadowFrame5.BorderColor3 = Color3.new(0, 0, 0)
ShadowFrame5.Transparency = 1
ShadowFrame5.Parent = LoadOutputProgramButton

local SelectType = Instance.new("ScrollingFrame")
SelectType.Name = "SelectType"
SelectType.Position = UDim2.new(0.5, 0, 0.5, 0)
SelectType.Size = UDim2.new(0, 150, 0, 200)
SelectType.BackgroundColor3 = Color3.new(0.109804, 0.0745098, 0.133333)
SelectType.BorderSizePixel = 0
SelectType.BorderColor3 = Color3.new(0, 0, 0)
SelectType.Visible = false
SelectType.ZIndex = 101
SelectType.AnchorPoint = Vector2.new(0.5, 0.5)
SelectType.Active = true
SelectType.CanvasSize = UDim2.new(0, 0, 0, 0)
SelectType.ScrollBarThickness = 6
SelectType.AutomaticCanvasSize = Enum.AutomaticSize.Y
SelectType.Parent = TDSHub

local UIStroke12 = Instance.new("UIStroke")
UIStroke12.Name = "UIStroke"
UIStroke12.Color = Color3.new(1, 0, 1)
UIStroke12.Thickness = 2
UIStroke12.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke12.Parent = SelectType

local Place = Instance.new("TextButton")
Place.Name = "Place"
Place.Position = UDim2.new(0, 0, 0, 5)
Place.Size = UDim2.new(1, 0, 0, 30)
Place.BackgroundColor3 = Color3.new(0, 0.784314, 0.470588)
Place.BorderSizePixel = 0
Place.BorderColor3 = Color3.new(0, 0, 0)
Place.Text = "Place"
Place.TextColor3 = Color3.new(1, 1, 1)
Place.TextSize = 14
Place.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Place.TextScaled = true
Place.TextWrapped = true
Place.Parent = SelectType

local Upgrade = Instance.new("TextButton")
Upgrade.Name = "Upgrade"
Upgrade.Position = UDim2.new(0, 0, 0, 40)
Upgrade.Size = UDim2.new(1, 0, 0, 30)
Upgrade.BackgroundColor3 = Color3.new(0.352941, 0.666667, 1)
Upgrade.BorderSizePixel = 0
Upgrade.BorderColor3 = Color3.new(0, 0, 0)
Upgrade.Text = "Upgrade"
Upgrade.TextColor3 = Color3.new(1, 1, 1)
Upgrade.TextSize = 14
Upgrade.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Upgrade.TextScaled = true
Upgrade.TextWrapped = true
Upgrade.Parent = SelectType

local Upgrade_all = Instance.new("TextButton")
Upgrade_all.Name = "Upgrade all"
Upgrade_all.Position = UDim2.new(0, 0, 0, 75)
Upgrade_all.Size = UDim2.new(1, 0, 0, 30)
Upgrade_all.BackgroundColor3 = Color3.new(0.784314, 0.509804, 1)
Upgrade_all.BorderSizePixel = 0
Upgrade_all.BorderColor3 = Color3.new(0, 0, 0)
Upgrade_all.Text = "Upgrade all"
Upgrade_all.TextColor3 = Color3.new(1, 1, 1)
Upgrade_all.TextSize = 14
Upgrade_all.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Upgrade_all.TextScaled = true
Upgrade_all.TextWrapped = true
Upgrade_all.Parent = SelectType

local Sell = Instance.new("TextButton")
Sell.Name = "Sell"
Sell.Position = UDim2.new(0, 0, 0, 110)
Sell.Size = UDim2.new(1, 0, 0, 30)
Sell.BackgroundColor3 = Color3.new(1, 0.372549, 0.372549)
Sell.BorderSizePixel = 0
Sell.BorderColor3 = Color3.new(0, 0, 0)
Sell.Text = "Sell"
Sell.TextColor3 = Color3.new(1, 1, 1)
Sell.TextSize = 14
Sell.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Sell.TextScaled = true
Sell.TextWrapped = true
Sell.Parent = SelectType

local Wait = Instance.new("TextButton")
Wait.Name = "Wait"
Wait.Position = UDim2.new(0, 0, 0, 145)
Wait.Size = UDim2.new(1, 0, 0, 30)
Wait.BackgroundColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Wait.BorderSizePixel = 0
Wait.BorderColor3 = Color3.new(0, 0, 0)
Wait.Text = "Wait"
Wait.TextColor3 = Color3.new(1, 1, 1)
Wait.TextSize = 14
Wait.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Wait.TextScaled = true
Wait.TextWrapped = true
Wait.Parent = SelectType

local PlaceSetting = Instance.new("Frame")
PlaceSetting.Name = "PlaceSetting"
PlaceSetting.Position = UDim2.new(0.5, 0, 0.5, 0)
PlaceSetting.Size = UDim2.new(0, 350, 0, 200)
PlaceSetting.BackgroundColor3 = Color3.new(0.109804, 0.0745098, 0.133333)
PlaceSetting.BorderSizePixel = 0
PlaceSetting.BorderColor3 = Color3.new(0, 0, 0)
PlaceSetting.Visible = false
PlaceSetting.ZIndex = 102
PlaceSetting.AnchorPoint = Vector2.new(0.5, 0.5)
PlaceSetting.Parent = TDSHub

local LineX3 = Instance.new("Frame")
LineX3.Name = "LineX"
LineX3.Position = UDim2.new(0.5, 0, 0, 0)
LineX3.Size = UDim2.new(1, 0, 0.01, 0)
LineX3.BackgroundColor3 = Color3.new(1, 0, 1)
LineX3.BorderSizePixel = 0
LineX3.BorderColor3 = Color3.new(0, 0, 0)
LineX3.AnchorPoint = Vector2.new(0.5, 0.5)
LineX3.Parent = PlaceSetting

local Tower = Instance.new("TextBox")
Tower.Name = "Tower"
Tower.Position = UDim2.new(0.25, 0, 0.5, 0)
Tower.Size = UDim2.new(0, 150, 0, 30)
Tower.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Tower.BorderSizePixel = 0
Tower.BorderColor3 = Color3.new(0, 0, 0)
Tower.AnchorPoint = Vector2.new(0.5, 0.5)
Tower.Text = ""
Tower.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Tower.TextSize = 14
Tower.FontFace = Font.new("rbxasset://fonts/families/Sarpanch.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
Tower.TextScaled = true
Tower.TextWrapped = true
Tower.PlaceholderText = "..."
Tower.Parent = PlaceSetting

local LineX4 = Instance.new("Frame")
LineX4.Name = "LineX"
LineX4.Position = UDim2.new(0.5, 0, 1, 0)
LineX4.Size = UDim2.new(1, 0, 0.01, 0)
LineX4.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX4.BorderSizePixel = 0
LineX4.BorderColor3 = Color3.new(0, 0, 0)
LineX4.AnchorPoint = Vector2.new(0.5, 0.5)
LineX4.Parent = Tower

local TitleTower = Instance.new("TextLabel")
TitleTower.Name = "TitleTower"
TitleTower.Position = UDim2.new(0.25, 0, 0.35, 0)
TitleTower.Size = UDim2.new(0, 125, 0, 30)
TitleTower.BackgroundColor3 = Color3.new(1, 1, 1)
TitleTower.BackgroundTransparency = 1
TitleTower.BorderSizePixel = 0
TitleTower.BorderColor3 = Color3.new(0, 0, 0)
TitleTower.AnchorPoint = Vector2.new(0.5, 0.5)
TitleTower.Transparency = 1
TitleTower.Text = "Tower name"
TitleTower.TextColor3 = Color3.new(1, 0, 1)
TitleTower.TextSize = 14
TitleTower.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleTower.TextScaled = true
TitleTower.TextWrapped = true
TitleTower.Parent = PlaceSetting

local SaveButton = Instance.new("TextButton")
SaveButton.Name = "SaveButton"
SaveButton.Position = UDim2.new(0.7, 0, 0.775, 0)
SaveButton.Size = UDim2.new(0, 100, 0, 40)
SaveButton.BackgroundColor3 = Color3.new(0, 0.862745, 0.388235)
SaveButton.BorderSizePixel = 0
SaveButton.BorderColor3 = Color3.new(0, 0, 0)
SaveButton.Text = "Save"
SaveButton.TextColor3 = Color3.new(1, 1, 1)
SaveButton.TextSize = 30
SaveButton.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
SaveButton.TextWrapped = true
SaveButton.Parent = PlaceSetting

local UICorner13 = Instance.new("UICorner")
UICorner13.Name = "UICorner"
UICorner13.CornerRadius = UDim.new(0.15, 0)
UICorner13.Parent = SaveButton

local Position = Instance.new("ScrollingFrame")
Position.Name = "Position"
Position.Position = UDim2.new(0.5, 0, 0.085, 0)
Position.Size = UDim2.new(0, 165, 0, 125)
Position.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Position.BorderSizePixel = 0
Position.BorderColor3 = Color3.new(0, 0, 0)
Position.Active = true
Position.CanvasSize = UDim2.new(0, 0, 0, 0)
Position.ScrollBarThickness = 4
Position.AutomaticCanvasSize = Enum.AutomaticSize.Y
Position.Parent = PlaceSetting

local PositionSample = Instance.new("TextButton")
PositionSample.Name = "PositionSample"
PositionSample.Size = UDim2.new(1, 0, 0, 20)
PositionSample.BackgroundColor3 = Color3.new(0.686275, 0.392157, 0.686275)
PositionSample.BorderSizePixel = 0
PositionSample.BorderColor3 = Color3.new(0, 0, 0)
PositionSample.Text = "0, 0, 0"
PositionSample.TextColor3 = Color3.new(1, 1, 1)
PositionSample.TextSize = 20
PositionSample.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
PositionSample.TextWrapped = true
PositionSample.TextXAlignment = Enum.TextXAlignment.Left
PositionSample.Parent = Position

local AddPositionButton = Instance.new("TextButton")
AddPositionButton.Name = "AddPositionButton"
AddPositionButton.Position = UDim2.new(0.075, 0, 0.7, 0)
AddPositionButton.Size = UDim2.new(0, 125, 0, 40)
AddPositionButton.BackgroundColor3 = Color3.new(0.686275, 0.392157, 0.686275)
AddPositionButton.BorderSizePixel = 0
AddPositionButton.BorderColor3 = Color3.new(0, 0, 0)
AddPositionButton.Text = "Add position"
AddPositionButton.TextColor3 = Color3.new(1, 1, 1)
AddPositionButton.TextSize = 17
AddPositionButton.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
AddPositionButton.Parent = PlaceSetting

local UICorner14 = Instance.new("UICorner")
UICorner14.Name = "UICorner"
UICorner14.CornerRadius = UDim.new(0.15, 0)
UICorner14.Parent = AddPositionButton

local UIStroke13 = Instance.new("UIStroke")
UIStroke13.Name = "UIStroke"
UIStroke13.Color = Color3.new(0, 1, 0.74902)
UIStroke13.Thickness = 3
UIStroke13.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke13.Parent = AddPositionButton

local ShadowFrame6 = Instance.new("Frame")
ShadowFrame6.Name = "ShadowFrame"
ShadowFrame6.Size = UDim2.new(1, 0, 1, 0)
ShadowFrame6.BackgroundColor3 = Color3.new(0, 0, 0)
ShadowFrame6.BackgroundTransparency = 1
ShadowFrame6.BorderSizePixel = 0
ShadowFrame6.BorderColor3 = Color3.new(0, 0, 0)
ShadowFrame6.Transparency = 1
ShadowFrame6.Parent = AddPositionButton

local UICorner15 = Instance.new("UICorner")
UICorner15.Name = "UICorner"
UICorner15.CornerRadius = UDim.new(0.15, 0)
UICorner15.Parent = ShadowFrame6

local CancelButton = Instance.new("TextButton")
CancelButton.Name = "CancelButton"
CancelButton.Position = UDim2.new(0.47, 0, 0.775, 0)
CancelButton.Size = UDim2.new(0, 75, 0, 40)
CancelButton.BackgroundColor3 = Color3.new(0.862745, 0.196078, 0.196078)
CancelButton.BorderSizePixel = 0
CancelButton.BorderColor3 = Color3.new(0, 0, 0)
CancelButton.Text = "Cancel"
CancelButton.TextColor3 = Color3.new(1, 1, 1)
CancelButton.TextSize = 20
CancelButton.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
CancelButton.TextWrapped = true
CancelButton.Parent = PlaceSetting

local UICorner16 = Instance.new("UICorner")
UICorner16.Name = "UICorner"
UICorner16.CornerRadius = UDim.new(0.15, 0)
UICorner16.Parent = CancelButton

local Title3 = Instance.new("TextLabel")
Title3.Name = "Title"
Title3.Position = UDim2.new(0.02, 0, 0.00571429, 0)
Title3.Size = UDim2.new(0, 150, 0, 40)
Title3.BackgroundColor3 = Color3.new(1, 1, 1)
Title3.BackgroundTransparency = 1
Title3.BorderSizePixel = 0
Title3.BorderColor3 = Color3.new(0, 0, 0)
Title3.Transparency = 1
Title3.Text = '<font color="rgb(255,0,255)">Place</font> program setting'
Title3.TextColor3 = Color3.new(0.588235, 0, 1)
Title3.TextSize = 20
Title3.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Title3.TextScaled = true
Title3.TextWrapped = true
Title3.TextXAlignment = Enum.TextXAlignment.Left
Title3.RichText = true
Title3.Parent = PlaceSetting

local UpgradeSetting = Instance.new("Frame")
UpgradeSetting.Name = "UpgradeSetting"
UpgradeSetting.Position = UDim2.new(0.5, 0, 0.5, 0)
UpgradeSetting.Size = UDim2.new(0, 350, 0, 200)
UpgradeSetting.BackgroundColor3 = Color3.new(0.109804, 0.0745098, 0.133333)
UpgradeSetting.BorderSizePixel = 0
UpgradeSetting.BorderColor3 = Color3.new(0, 0, 0)
UpgradeSetting.Visible = false
UpgradeSetting.ZIndex = 102
UpgradeSetting.AnchorPoint = Vector2.new(0.5, 0.5)
UpgradeSetting.Parent = TDSHub

local LineX5 = Instance.new("Frame")
LineX5.Name = "LineX"
LineX5.Position = UDim2.new(0.5, 0, 0, 0)
LineX5.Size = UDim2.new(1, 0, 0.01, 0)
LineX5.BackgroundColor3 = Color3.new(1, 0, 1)
LineX5.BorderSizePixel = 0
LineX5.BorderColor3 = Color3.new(0, 0, 0)
LineX5.AnchorPoint = Vector2.new(0.5, 0.5)
LineX5.Parent = UpgradeSetting

local Tower2 = Instance.new("TextBox")
Tower2.Name = "Tower"
Tower2.Position = UDim2.new(0.225, 0, 0.5, 0)
Tower2.Size = UDim2.new(0, 150, 0, 30)
Tower2.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Tower2.BorderSizePixel = 0
Tower2.BorderColor3 = Color3.new(0, 0, 0)
Tower2.AnchorPoint = Vector2.new(0.5, 0.5)
Tower2.Text = ""
Tower2.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Tower2.TextSize = 14
Tower2.FontFace = Font.new("rbxasset://fonts/families/Sarpanch.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
Tower2.TextScaled = true
Tower2.TextWrapped = true
Tower2.PlaceholderText = "..."
Tower2.Parent = UpgradeSetting

local LineX6 = Instance.new("Frame")
LineX6.Name = "LineX"
LineX6.Position = UDim2.new(0.5, 0, 1, 0)
LineX6.Size = UDim2.new(1, 0, 0.01, 0)
LineX6.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX6.BorderSizePixel = 0
LineX6.BorderColor3 = Color3.new(0, 0, 0)
LineX6.AnchorPoint = Vector2.new(0.5, 0.5)
LineX6.Parent = Tower2

local TitleTower2 = Instance.new("TextLabel")
TitleTower2.Name = "TitleTower"
TitleTower2.Position = UDim2.new(0.225, 0, 0.35, 0)
TitleTower2.Size = UDim2.new(0, 125, 0, 30)
TitleTower2.BackgroundColor3 = Color3.new(1, 1, 1)
TitleTower2.BackgroundTransparency = 1
TitleTower2.BorderSizePixel = 0
TitleTower2.BorderColor3 = Color3.new(0, 0, 0)
TitleTower2.AnchorPoint = Vector2.new(0.5, 0.5)
TitleTower2.Transparency = 1
TitleTower2.Text = "Tower name"
TitleTower2.TextColor3 = Color3.new(1, 0, 1)
TitleTower2.TextSize = 14
TitleTower2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleTower2.TextScaled = true
TitleTower2.TextWrapped = true
TitleTower2.Parent = UpgradeSetting

local SaveButton2 = Instance.new("TextButton")
SaveButton2.Name = "SaveButton"
SaveButton2.Position = UDim2.new(0.7, 0, 0.775, 0)
SaveButton2.Size = UDim2.new(0, 100, 0, 40)
SaveButton2.BackgroundColor3 = Color3.new(0, 0.862745, 0.388235)
SaveButton2.BorderSizePixel = 0
SaveButton2.BorderColor3 = Color3.new(0, 0, 0)
SaveButton2.Text = "Save"
SaveButton2.TextColor3 = Color3.new(1, 1, 1)
SaveButton2.TextSize = 30
SaveButton2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
SaveButton2.TextWrapped = true
SaveButton2.Parent = UpgradeSetting

local UICorner17 = Instance.new("UICorner")
UICorner17.Name = "UICorner"
UICorner17.CornerRadius = UDim.new(0.15, 0)
UICorner17.Parent = SaveButton2

local CancelButton2 = Instance.new("TextButton")
CancelButton2.Name = "CancelButton"
CancelButton2.Position = UDim2.new(0.47, 0, 0.775, 0)
CancelButton2.Size = UDim2.new(0, 75, 0, 40)
CancelButton2.BackgroundColor3 = Color3.new(0.862745, 0.196078, 0.196078)
CancelButton2.BorderSizePixel = 0
CancelButton2.BorderColor3 = Color3.new(0, 0, 0)
CancelButton2.Text = "Cancel"
CancelButton2.TextColor3 = Color3.new(1, 1, 1)
CancelButton2.TextSize = 20
CancelButton2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
CancelButton2.TextWrapped = true
CancelButton2.Parent = UpgradeSetting

local UICorner18 = Instance.new("UICorner")
UICorner18.Name = "UICorner"
UICorner18.CornerRadius = UDim.new(0.15, 0)
UICorner18.Parent = CancelButton2

local LevelTarget = Instance.new("TextBox")
LevelTarget.Name = "LevelTarget"
LevelTarget.Position = UDim2.new(0.225, 0, 0.875, 0)
LevelTarget.Size = UDim2.new(0, 150, 0, 30)
LevelTarget.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
LevelTarget.BorderSizePixel = 0
LevelTarget.BorderColor3 = Color3.new(0, 0, 0)
LevelTarget.AnchorPoint = Vector2.new(0.5, 0.5)
LevelTarget.Text = ""
LevelTarget.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
LevelTarget.TextSize = 14
LevelTarget.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
LevelTarget.TextScaled = true
LevelTarget.TextWrapped = true
LevelTarget.PlaceholderText = "..."
LevelTarget.Parent = UpgradeSetting

local LineX7 = Instance.new("Frame")
LineX7.Name = "LineX"
LineX7.Position = UDim2.new(0.5, 0, 1, 0)
LineX7.Size = UDim2.new(1, 0, 0.01, 0)
LineX7.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX7.BorderSizePixel = 0
LineX7.BorderColor3 = Color3.new(0, 0, 0)
LineX7.AnchorPoint = Vector2.new(0.5, 0.5)
LineX7.Parent = LevelTarget

local TitleLVL = Instance.new("TextLabel")
TitleLVL.Name = "TitleLVL"
TitleLVL.Position = UDim2.new(0.225, 0, 0.725, 0)
TitleLVL.Size = UDim2.new(0, 125, 0, 30)
TitleLVL.BackgroundColor3 = Color3.new(1, 1, 1)
TitleLVL.BackgroundTransparency = 1
TitleLVL.BorderSizePixel = 0
TitleLVL.BorderColor3 = Color3.new(0, 0, 0)
TitleLVL.AnchorPoint = Vector2.new(0.5, 0.5)
TitleLVL.Transparency = 1
TitleLVL.Text = "Level target"
TitleLVL.TextColor3 = Color3.new(1, 0, 1)
TitleLVL.TextSize = 14
TitleLVL.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleLVL.TextScaled = true
TitleLVL.TextWrapped = true
TitleLVL.Parent = UpgradeSetting

local Orther = Instance.new("TextBox")
Orther.Name = "Orther"
Orther.Position = UDim2.new(0.6, 0, 0.65, 0)
Orther.Size = UDim2.new(0, 75, 0, 30)
Orther.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Orther.BorderSizePixel = 0
Orther.BorderColor3 = Color3.new(0, 0, 0)
Orther.AnchorPoint = Vector2.new(0.5, 0.5)
Orther.Text = ""
Orther.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Orther.TextSize = 14
Orther.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Orther.TextScaled = true
Orther.TextWrapped = true
Orther.PlaceholderText = "..."
Orther.Parent = UpgradeSetting

local LineX8 = Instance.new("Frame")
LineX8.Name = "LineX"
LineX8.Position = UDim2.new(0.5, 0, 1, 0)
LineX8.Size = UDim2.new(1, 0, 0.01, 0)
LineX8.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX8.BorderSizePixel = 0
LineX8.BorderColor3 = Color3.new(0, 0, 0)
LineX8.AnchorPoint = Vector2.new(0.5, 0.5)
LineX8.Parent = Orther

local TitleOrther = Instance.new("TextLabel")
TitleOrther.Name = "TitleOrther"
TitleOrther.Position = UDim2.new(0.6, 0, 0.525, 0)
TitleOrther.Size = UDim2.new(0, 75, 0, 20)
TitleOrther.BackgroundColor3 = Color3.new(1, 1, 1)
TitleOrther.BackgroundTransparency = 1
TitleOrther.BorderSizePixel = 0
TitleOrther.BorderColor3 = Color3.new(0, 0, 0)
TitleOrther.AnchorPoint = Vector2.new(0.5, 0.5)
TitleOrther.Transparency = 1
TitleOrther.Text = "Orther"
TitleOrther.TextColor3 = Color3.new(1, 0, 1)
TitleOrther.TextSize = 14
TitleOrther.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleOrther.TextScaled = true
TitleOrther.TextWrapped = true
TitleOrther.Parent = UpgradeSetting

local Interval = Instance.new("TextBox")
Interval.Name = "Interval"
Interval.Position = UDim2.new(0.85, 0, 0.65, 0)
Interval.Size = UDim2.new(0, 75, 0, 30)
Interval.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Interval.BorderSizePixel = 0
Interval.BorderColor3 = Color3.new(0, 0, 0)
Interval.AnchorPoint = Vector2.new(0.5, 0.5)
Interval.Text = ""
Interval.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Interval.TextSize = 14
Interval.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Interval.TextScaled = true
Interval.TextWrapped = true
Interval.PlaceholderText = "..."
Interval.Parent = UpgradeSetting

local LineX9 = Instance.new("Frame")
LineX9.Name = "LineX"
LineX9.Position = UDim2.new(0.5, 0, 1, 0)
LineX9.Size = UDim2.new(1, 0, 0.01, 0)
LineX9.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX9.BorderSizePixel = 0
LineX9.BorderColor3 = Color3.new(0, 0, 0)
LineX9.AnchorPoint = Vector2.new(0.5, 0.5)
LineX9.Parent = Interval

local TitleInterval = Instance.new("TextLabel")
TitleInterval.Name = "TitleInterval"
TitleInterval.Position = UDim2.new(0.85, 0, 0.525, 0)
TitleInterval.Size = UDim2.new(0, 75, 0, 20)
TitleInterval.BackgroundColor3 = Color3.new(1, 1, 1)
TitleInterval.BackgroundTransparency = 1
TitleInterval.BorderSizePixel = 0
TitleInterval.BorderColor3 = Color3.new(0, 0, 0)
TitleInterval.AnchorPoint = Vector2.new(0.5, 0.5)
TitleInterval.Transparency = 1
TitleInterval.Text = "Delay"
TitleInterval.TextColor3 = Color3.new(1, 0, 1)
TitleInterval.TextSize = 14
TitleInterval.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleInterval.TextScaled = true
TitleInterval.TextWrapped = true
TitleInterval.Parent = UpgradeSetting

local Branch = Instance.new("TextButton")
Branch.Name = "Branch"
Branch.Position = UDim2.new(0, 180, 0, 50)
Branch.Size = UDim2.new(0, 150, 0, 35)
Branch.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Branch.BorderSizePixel = 0
Branch.BorderColor3 = Color3.new(0, 0, 0)
Branch.Text = "Above"
Branch.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Branch.TextSize = 30
Branch.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Branch.Parent = UpgradeSetting

local TitleBranch = Instance.new("TextLabel")
TitleBranch.Name = "TitleBranch"
TitleBranch.Position = UDim2.new(0.725, 0, 0.175, 0)
TitleBranch.Size = UDim2.new(0, 100, 0, 30)
TitleBranch.BackgroundColor3 = Color3.new(1, 1, 1)
TitleBranch.BackgroundTransparency = 1
TitleBranch.BorderSizePixel = 0
TitleBranch.BorderColor3 = Color3.new(0, 0, 0)
TitleBranch.AnchorPoint = Vector2.new(0.5, 0.5)
TitleBranch.Transparency = 1
TitleBranch.Text = "Branch"
TitleBranch.TextColor3 = Color3.new(1, 0, 1)
TitleBranch.TextSize = 14
TitleBranch.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleBranch.TextScaled = true
TitleBranch.TextWrapped = true
TitleBranch.Parent = UpgradeSetting

local Title4 = Instance.new("TextLabel")
Title4.Name = "Title"
Title4.Position = UDim2.new(0.02, 0, 0.00571429, 0)
Title4.Size = UDim2.new(0, 150, 0, 40)
Title4.BackgroundColor3 = Color3.new(1, 1, 1)
Title4.BackgroundTransparency = 1
Title4.BorderSizePixel = 0
Title4.BorderColor3 = Color3.new(0, 0, 0)
Title4.Transparency = 1
Title4.Text = '<font color="rgb(255,0,255)">Upgrade</font> program setting'
Title4.TextColor3 = Color3.new(0.588235, 0, 1)
Title4.TextSize = 20
Title4.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Title4.TextScaled = true
Title4.TextWrapped = true
Title4.TextXAlignment = Enum.TextXAlignment.Left
Title4.RichText = true
Title4.Parent = UpgradeSetting

local UpgradeAllSetting = Instance.new("Frame")
UpgradeAllSetting.Name = "UpgradeAllSetting"
UpgradeAllSetting.Position = UDim2.new(0.5, 0, 0.5, 0)
UpgradeAllSetting.Size = UDim2.new(0, 350, 0, 200)
UpgradeAllSetting.BackgroundColor3 = Color3.new(0.109804, 0.0745098, 0.133333)
UpgradeAllSetting.BorderSizePixel = 0
UpgradeAllSetting.BorderColor3 = Color3.new(0, 0, 0)
UpgradeAllSetting.Visible = false
UpgradeAllSetting.ZIndex = 102
UpgradeAllSetting.AnchorPoint = Vector2.new(0.5, 0.5)
UpgradeAllSetting.Parent = TDSHub

local LineX10 = Instance.new("Frame")
LineX10.Name = "LineX"
LineX10.Position = UDim2.new(0.5, 0, 0, 0)
LineX10.Size = UDim2.new(1, 0, 0.01, 0)
LineX10.BackgroundColor3 = Color3.new(1, 0, 1)
LineX10.BorderSizePixel = 0
LineX10.BorderColor3 = Color3.new(0, 0, 0)
LineX10.AnchorPoint = Vector2.new(0.5, 0.5)
LineX10.Parent = UpgradeAllSetting

local Tower3 = Instance.new("TextBox")
Tower3.Name = "Tower"
Tower3.Position = UDim2.new(0.225, 0, 0.5, 0)
Tower3.Size = UDim2.new(0, 150, 0, 30)
Tower3.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Tower3.BorderSizePixel = 0
Tower3.BorderColor3 = Color3.new(0, 0, 0)
Tower3.AnchorPoint = Vector2.new(0.5, 0.5)
Tower3.Text = ""
Tower3.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Tower3.TextSize = 14
Tower3.FontFace = Font.new("rbxasset://fonts/families/Sarpanch.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
Tower3.TextScaled = true
Tower3.TextWrapped = true
Tower3.PlaceholderText = "..."
Tower3.Parent = UpgradeAllSetting

local LineX11 = Instance.new("Frame")
LineX11.Name = "LineX"
LineX11.Position = UDim2.new(0.5, 0, 1, 0)
LineX11.Size = UDim2.new(1, 0, 0.01, 0)
LineX11.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX11.BorderSizePixel = 0
LineX11.BorderColor3 = Color3.new(0, 0, 0)
LineX11.AnchorPoint = Vector2.new(0.5, 0.5)
LineX11.Parent = Tower3

local TitleTower3 = Instance.new("TextLabel")
TitleTower3.Name = "TitleTower"
TitleTower3.Position = UDim2.new(0.225, 0, 0.35, 0)
TitleTower3.Size = UDim2.new(0, 125, 0, 30)
TitleTower3.BackgroundColor3 = Color3.new(1, 1, 1)
TitleTower3.BackgroundTransparency = 1
TitleTower3.BorderSizePixel = 0
TitleTower3.BorderColor3 = Color3.new(0, 0, 0)
TitleTower3.AnchorPoint = Vector2.new(0.5, 0.5)
TitleTower3.Transparency = 1
TitleTower3.Text = "Tower name"
TitleTower3.TextColor3 = Color3.new(1, 0, 1)
TitleTower3.TextSize = 14
TitleTower3.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleTower3.TextScaled = true
TitleTower3.TextWrapped = true
TitleTower3.Parent = UpgradeAllSetting

local SaveButton3 = Instance.new("TextButton")
SaveButton3.Name = "SaveButton"
SaveButton3.Position = UDim2.new(0.7, 0, 0.775, 0)
SaveButton3.Size = UDim2.new(0, 100, 0, 40)
SaveButton3.BackgroundColor3 = Color3.new(0, 0.862745, 0.388235)
SaveButton3.BorderSizePixel = 0
SaveButton3.BorderColor3 = Color3.new(0, 0, 0)
SaveButton3.Text = "Save"
SaveButton3.TextColor3 = Color3.new(1, 1, 1)
SaveButton3.TextSize = 30
SaveButton3.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
SaveButton3.TextWrapped = true
SaveButton3.Parent = UpgradeAllSetting

local UICorner19 = Instance.new("UICorner")
UICorner19.Name = "UICorner"
UICorner19.CornerRadius = UDim.new(0.15, 0)
UICorner19.Parent = SaveButton3

local CancelButton3 = Instance.new("TextButton")
CancelButton3.Name = "CancelButton"
CancelButton3.Position = UDim2.new(0.47, 0, 0.775, 0)
CancelButton3.Size = UDim2.new(0, 75, 0, 40)
CancelButton3.BackgroundColor3 = Color3.new(0.862745, 0.196078, 0.196078)
CancelButton3.BorderSizePixel = 0
CancelButton3.BorderColor3 = Color3.new(0, 0, 0)
CancelButton3.Text = "Cancel"
CancelButton3.TextColor3 = Color3.new(1, 1, 1)
CancelButton3.TextSize = 20
CancelButton3.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
CancelButton3.TextWrapped = true
CancelButton3.Parent = UpgradeAllSetting

local UICorner20 = Instance.new("UICorner")
UICorner20.Name = "UICorner"
UICorner20.CornerRadius = UDim.new(0.15, 0)
UICorner20.Parent = CancelButton3

local LevelTarget2 = Instance.new("TextBox")
LevelTarget2.Name = "LevelTarget"
LevelTarget2.Position = UDim2.new(0.225, 0, 0.875, 0)
LevelTarget2.Size = UDim2.new(0, 150, 0, 30)
LevelTarget2.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
LevelTarget2.BorderSizePixel = 0
LevelTarget2.BorderColor3 = Color3.new(0, 0, 0)
LevelTarget2.AnchorPoint = Vector2.new(0.5, 0.5)
LevelTarget2.Text = ""
LevelTarget2.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
LevelTarget2.TextSize = 14
LevelTarget2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
LevelTarget2.TextScaled = true
LevelTarget2.TextWrapped = true
LevelTarget2.PlaceholderText = "..."
LevelTarget2.Parent = UpgradeAllSetting

local LineX12 = Instance.new("Frame")
LineX12.Name = "LineX"
LineX12.Position = UDim2.new(0.5, 0, 1, 0)
LineX12.Size = UDim2.new(1, 0, 0.01, 0)
LineX12.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX12.BorderSizePixel = 0
LineX12.BorderColor3 = Color3.new(0, 0, 0)
LineX12.AnchorPoint = Vector2.new(0.5, 0.5)
LineX12.Parent = LevelTarget2

local TitleLVL2 = Instance.new("TextLabel")
TitleLVL2.Name = "TitleLVL"
TitleLVL2.Position = UDim2.new(0.225, 0, 0.725, 0)
TitleLVL2.Size = UDim2.new(0, 125, 0, 30)
TitleLVL2.BackgroundColor3 = Color3.new(1, 1, 1)
TitleLVL2.BackgroundTransparency = 1
TitleLVL2.BorderSizePixel = 0
TitleLVL2.BorderColor3 = Color3.new(0, 0, 0)
TitleLVL2.AnchorPoint = Vector2.new(0.5, 0.5)
TitleLVL2.Transparency = 1
TitleLVL2.Text = "Level target"
TitleLVL2.TextColor3 = Color3.new(1, 0, 1)
TitleLVL2.TextSize = 14
TitleLVL2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleLVL2.TextScaled = true
TitleLVL2.TextWrapped = true
TitleLVL2.Parent = UpgradeAllSetting

local TitleOneByOne = Instance.new("TextLabel")
TitleOneByOne.Name = "TitleOneByOne"
TitleOneByOne.Position = UDim2.new(0.6, 0, 0.525, 0)
TitleOneByOne.Size = UDim2.new(0, 75, 0, 20)
TitleOneByOne.BackgroundColor3 = Color3.new(1, 1, 1)
TitleOneByOne.BackgroundTransparency = 1
TitleOneByOne.BorderSizePixel = 0
TitleOneByOne.BorderColor3 = Color3.new(0, 0, 0)
TitleOneByOne.AnchorPoint = Vector2.new(0.5, 0.5)
TitleOneByOne.Transparency = 1
TitleOneByOne.Text = "1 by 1"
TitleOneByOne.TextColor3 = Color3.new(1, 0, 1)
TitleOneByOne.TextSize = 14
TitleOneByOne.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleOneByOne.TextScaled = true
TitleOneByOne.TextWrapped = true
TitleOneByOne.Parent = UpgradeAllSetting

local Interval2 = Instance.new("TextBox")
Interval2.Name = "Interval"
Interval2.Position = UDim2.new(0.85, 0, 0.65, 0)
Interval2.Size = UDim2.new(0, 75, 0, 30)
Interval2.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Interval2.BorderSizePixel = 0
Interval2.BorderColor3 = Color3.new(0, 0, 0)
Interval2.AnchorPoint = Vector2.new(0.5, 0.5)
Interval2.Text = ""
Interval2.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Interval2.TextSize = 14
Interval2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Interval2.TextScaled = true
Interval2.TextWrapped = true
Interval2.PlaceholderText = "..."
Interval2.Parent = UpgradeAllSetting

local LineX13 = Instance.new("Frame")
LineX13.Name = "LineX"
LineX13.Position = UDim2.new(0.5, 0, 1, 0)
LineX13.Size = UDim2.new(1, 0, 0.01, 0)
LineX13.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX13.BorderSizePixel = 0
LineX13.BorderColor3 = Color3.new(0, 0, 0)
LineX13.AnchorPoint = Vector2.new(0.5, 0.5)
LineX13.Parent = Interval2

local TitleInterval2 = Instance.new("TextLabel")
TitleInterval2.Name = "TitleInterval"
TitleInterval2.Position = UDim2.new(0.85, 0, 0.525, 0)
TitleInterval2.Size = UDim2.new(0, 75, 0, 20)
TitleInterval2.BackgroundColor3 = Color3.new(1, 1, 1)
TitleInterval2.BackgroundTransparency = 1
TitleInterval2.BorderSizePixel = 0
TitleInterval2.BorderColor3 = Color3.new(0, 0, 0)
TitleInterval2.AnchorPoint = Vector2.new(0.5, 0.5)
TitleInterval2.Transparency = 1
TitleInterval2.Text = "Delay"
TitleInterval2.TextColor3 = Color3.new(1, 0, 1)
TitleInterval2.TextSize = 14
TitleInterval2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleInterval2.TextScaled = true
TitleInterval2.TextWrapped = true
TitleInterval2.Parent = UpgradeAllSetting

local Branch2 = Instance.new("TextButton")
Branch2.Name = "Branch"
Branch2.Position = UDim2.new(0, 180, 0, 50)
Branch2.Size = UDim2.new(0, 150, 0, 35)
Branch2.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Branch2.BorderSizePixel = 0
Branch2.BorderColor3 = Color3.new(0, 0, 0)
Branch2.Text = "Above"
Branch2.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Branch2.TextSize = 30
Branch2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Branch2.Parent = UpgradeAllSetting

local TitleBranch2 = Instance.new("TextLabel")
TitleBranch2.Name = "TitleBranch"
TitleBranch2.Position = UDim2.new(0.725, 0, 0.175, 0)
TitleBranch2.Size = UDim2.new(0, 100, 0, 30)
TitleBranch2.BackgroundColor3 = Color3.new(1, 1, 1)
TitleBranch2.BackgroundTransparency = 1
TitleBranch2.BorderSizePixel = 0
TitleBranch2.BorderColor3 = Color3.new(0, 0, 0)
TitleBranch2.AnchorPoint = Vector2.new(0.5, 0.5)
TitleBranch2.Transparency = 1
TitleBranch2.Text = "Branch"
TitleBranch2.TextColor3 = Color3.new(1, 0, 1)
TitleBranch2.TextSize = 14
TitleBranch2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleBranch2.TextScaled = true
TitleBranch2.TextWrapped = true
TitleBranch2.Parent = UpgradeAllSetting

local One_by_one = Instance.new("TextButton")
One_by_one.Name = "One_by_one"
One_by_one.Position = UDim2.new(0.6, 0, 0.65, 0)
One_by_one.Size = UDim2.new(0, 75, 0, 30)
One_by_one.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
One_by_one.BorderSizePixel = 0
One_by_one.BorderColor3 = Color3.new(0, 0, 0)
One_by_one.AnchorPoint = Vector2.new(0.5, 0.5)
One_by_one.Text = "Off"
One_by_one.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
One_by_one.TextSize = 25
One_by_one.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
One_by_one.Parent = UpgradeAllSetting

local Title5 = Instance.new("TextLabel")
Title5.Name = "Title"
Title5.Position = UDim2.new(0.02, 0, 0.00571429, 0)
Title5.Size = UDim2.new(0, 150, 0, 40)
Title5.BackgroundColor3 = Color3.new(1, 1, 1)
Title5.BackgroundTransparency = 1
Title5.BorderSizePixel = 0
Title5.BorderColor3 = Color3.new(0, 0, 0)
Title5.Transparency = 1
Title5.Text = '<font color="rgb(255,0,255)">Upgrade all</font> program setting'
Title5.TextColor3 = Color3.new(0.588235, 0, 1)
Title5.TextSize = 20
Title5.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Title5.TextScaled = true
Title5.TextWrapped = true
Title5.TextXAlignment = Enum.TextXAlignment.Left
Title5.RichText = true
Title5.Parent = UpgradeAllSetting

local SellSetting = Instance.new("Frame")
SellSetting.Name = "SellSetting"
SellSetting.Position = UDim2.new(0.5, 0, 0.5, 0)
SellSetting.Size = UDim2.new(0, 350, 0, 200)
SellSetting.BackgroundColor3 = Color3.new(0.109804, 0.0745098, 0.133333)
SellSetting.BorderSizePixel = 0
SellSetting.BorderColor3 = Color3.new(0, 0, 0)
SellSetting.Visible = false
SellSetting.ZIndex = 102
SellSetting.AnchorPoint = Vector2.new(0.5, 0.5)
SellSetting.Parent = TDSHub

local LineX14 = Instance.new("Frame")
LineX14.Name = "LineX"
LineX14.Position = UDim2.new(0.5, 0, 0, 0)
LineX14.Size = UDim2.new(1, 0, 0.01, 0)
LineX14.BackgroundColor3 = Color3.new(1, 0, 1)
LineX14.BorderSizePixel = 0
LineX14.BorderColor3 = Color3.new(0, 0, 0)
LineX14.AnchorPoint = Vector2.new(0.5, 0.5)
LineX14.Parent = SellSetting

local SaveButton4 = Instance.new("TextButton")
SaveButton4.Name = "SaveButton"
SaveButton4.Position = UDim2.new(0.7, 0, 0.775, 0)
SaveButton4.Size = UDim2.new(0, 100, 0, 40)
SaveButton4.BackgroundColor3 = Color3.new(0, 0.862745, 0.388235)
SaveButton4.BorderSizePixel = 0
SaveButton4.BorderColor3 = Color3.new(0, 0, 0)
SaveButton4.Text = "Save"
SaveButton4.TextColor3 = Color3.new(1, 1, 1)
SaveButton4.TextSize = 30
SaveButton4.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
SaveButton4.TextWrapped = true
SaveButton4.Parent = SellSetting

local UICorner21 = Instance.new("UICorner")
UICorner21.Name = "UICorner"
UICorner21.CornerRadius = UDim.new(0.15, 0)
UICorner21.Parent = SaveButton4

local CancelButton4 = Instance.new("TextButton")
CancelButton4.Name = "CancelButton"
CancelButton4.Position = UDim2.new(0.47, 0, 0.775, 0)
CancelButton4.Size = UDim2.new(0, 75, 0, 40)
CancelButton4.BackgroundColor3 = Color3.new(0.862745, 0.196078, 0.196078)
CancelButton4.BorderSizePixel = 0
CancelButton4.BorderColor3 = Color3.new(0, 0, 0)
CancelButton4.Text = "Cancel"
CancelButton4.TextColor3 = Color3.new(1, 1, 1)
CancelButton4.TextSize = 20
CancelButton4.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
CancelButton4.TextWrapped = true
CancelButton4.Parent = SellSetting

local UICorner22 = Instance.new("UICorner")
UICorner22.Name = "UICorner"
UICorner22.CornerRadius = UDim.new(0.15, 0)
UICorner22.Parent = CancelButton4

local Interval3 = Instance.new("TextBox")
Interval3.Name = "Interval"
Interval3.Position = UDim2.new(0.75, 0, 0.5, 0)
Interval3.Size = UDim2.new(0, 150, 0, 30)
Interval3.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Interval3.BorderSizePixel = 0
Interval3.BorderColor3 = Color3.new(0, 0, 0)
Interval3.AnchorPoint = Vector2.new(0.5, 0.5)
Interval3.Text = ""
Interval3.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Interval3.TextSize = 14
Interval3.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Interval3.TextScaled = true
Interval3.TextWrapped = true
Interval3.PlaceholderText = "..."
Interval3.Parent = SellSetting

local LineX15 = Instance.new("Frame")
LineX15.Name = "LineX"
LineX15.Position = UDim2.new(0.5, 0, 1, 0)
LineX15.Size = UDim2.new(1, 0, 0.01, 0)
LineX15.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX15.BorderSizePixel = 0
LineX15.BorderColor3 = Color3.new(0, 0, 0)
LineX15.AnchorPoint = Vector2.new(0.5, 0.5)
LineX15.Parent = Interval3

local TitleInterval3 = Instance.new("TextLabel")
TitleInterval3.Name = "TitleInterval"
TitleInterval3.Position = UDim2.new(0.75, 0, 0.35, 0)
TitleInterval3.Size = UDim2.new(0, 100, 0, 20)
TitleInterval3.BackgroundColor3 = Color3.new(1, 1, 1)
TitleInterval3.BackgroundTransparency = 1
TitleInterval3.BorderSizePixel = 0
TitleInterval3.BorderColor3 = Color3.new(0, 0, 0)
TitleInterval3.AnchorPoint = Vector2.new(0.5, 0.5)
TitleInterval3.Transparency = 1
TitleInterval3.Text = "Delay"
TitleInterval3.TextColor3 = Color3.new(1, 0, 1)
TitleInterval3.TextSize = 14
TitleInterval3.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleInterval3.TextScaled = true
TitleInterval3.TextWrapped = true
TitleInterval3.Parent = SellSetting

local TitleOrther2 = Instance.new("TextLabel")
TitleOrther2.Name = "TitleOrther"
TitleOrther2.Position = UDim2.new(0.225, 0, 0.7, 0)
TitleOrther2.Size = UDim2.new(0, 100, 0, 20)
TitleOrther2.BackgroundColor3 = Color3.new(1, 1, 1)
TitleOrther2.BackgroundTransparency = 1
TitleOrther2.BorderSizePixel = 0
TitleOrther2.BorderColor3 = Color3.new(0, 0, 0)
TitleOrther2.AnchorPoint = Vector2.new(0.5, 0.5)
TitleOrther2.Transparency = 1
TitleOrther2.Text = "Orther"
TitleOrther2.TextColor3 = Color3.new(1, 0, 1)
TitleOrther2.TextSize = 14
TitleOrther2.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleOrther2.TextScaled = true
TitleOrther2.TextWrapped = true
TitleOrther2.Parent = SellSetting

local OrtherButton = Instance.new("TextButton")
OrtherButton.Name = "OrtherButton"
OrtherButton.Position = UDim2.new(0.115, 0, 0.85, 0)
OrtherButton.Size = UDim2.new(0, 75, 0, 30)
OrtherButton.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
OrtherButton.BorderSizePixel = 0
OrtherButton.BorderColor3 = Color3.new(0, 0, 0)
OrtherButton.AnchorPoint = Vector2.new(0.5, 0.5)
OrtherButton.Text = "All"
OrtherButton.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
OrtherButton.TextSize = 25
OrtherButton.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
OrtherButton.Parent = SellSetting

local TitleTower4 = Instance.new("TextLabel")
TitleTower4.Name = "TitleTower"
TitleTower4.Position = UDim2.new(0.225, 0, 0.35, 0)
TitleTower4.Size = UDim2.new(0, 125, 0, 30)
TitleTower4.BackgroundColor3 = Color3.new(1, 1, 1)
TitleTower4.BackgroundTransparency = 1
TitleTower4.BorderSizePixel = 0
TitleTower4.BorderColor3 = Color3.new(0, 0, 0)
TitleTower4.AnchorPoint = Vector2.new(0.5, 0.5)
TitleTower4.Transparency = 1
TitleTower4.Text = "Tower name"
TitleTower4.TextColor3 = Color3.new(1, 0, 1)
TitleTower4.TextSize = 14
TitleTower4.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleTower4.TextScaled = true
TitleTower4.TextWrapped = true
TitleTower4.Parent = SellSetting

local Tower4 = Instance.new("TextBox")
Tower4.Name = "Tower"
Tower4.Position = UDim2.new(0.225, 0, 0.5, 0)
Tower4.Size = UDim2.new(0, 150, 0, 30)
Tower4.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Tower4.BorderSizePixel = 0
Tower4.BorderColor3 = Color3.new(0, 0, 0)
Tower4.AnchorPoint = Vector2.new(0.5, 0.5)
Tower4.Text = ""
Tower4.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Tower4.TextSize = 14
Tower4.FontFace = Font.new("rbxasset://fonts/families/Sarpanch.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
Tower4.TextScaled = true
Tower4.TextWrapped = true
Tower4.PlaceholderText = "..."
Tower4.Parent = SellSetting

local LineX16 = Instance.new("Frame")
LineX16.Name = "LineX"
LineX16.Position = UDim2.new(0.5, 0, 1, 0)
LineX16.Size = UDim2.new(1, 0, 0.01, 0)
LineX16.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX16.BorderSizePixel = 0
LineX16.BorderColor3 = Color3.new(0, 0, 0)
LineX16.AnchorPoint = Vector2.new(0.5, 0.5)
LineX16.Parent = Tower4

local OrtherTextbox = Instance.new("TextBox")
OrtherTextbox.Name = "OrtherTextbox"
OrtherTextbox.Position = UDim2.new(0.33, 0, 0.85, 0)
OrtherTextbox.Size = UDim2.new(0, 75, 0, 30)
OrtherTextbox.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
OrtherTextbox.BorderSizePixel = 0
OrtherTextbox.BorderColor3 = Color3.new(0, 0, 0)
OrtherTextbox.AnchorPoint = Vector2.new(0.5, 0.5)
OrtherTextbox.Text = ""
OrtherTextbox.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
OrtherTextbox.TextSize = 14
OrtherTextbox.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
OrtherTextbox.TextScaled = true
OrtherTextbox.TextWrapped = true
OrtherTextbox.PlaceholderText = "..."
OrtherTextbox.Parent = SellSetting

local LineX17 = Instance.new("Frame")
LineX17.Name = "LineX"
LineX17.Position = UDim2.new(0.5, 0, 1, 0)
LineX17.Size = UDim2.new(1, 0, 0.01, 0)
LineX17.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX17.BorderSizePixel = 0
LineX17.BorderColor3 = Color3.new(0, 0, 0)
LineX17.AnchorPoint = Vector2.new(0.5, 0.5)
LineX17.Parent = OrtherTextbox

local Title6 = Instance.new("TextLabel")
Title6.Name = "Title"
Title6.Position = UDim2.new(0.02, 0, 0.00571429, 0)
Title6.Size = UDim2.new(0, 150, 0, 40)
Title6.BackgroundColor3 = Color3.new(1, 1, 1)
Title6.BackgroundTransparency = 1
Title6.BorderSizePixel = 0
Title6.BorderColor3 = Color3.new(0, 0, 0)
Title6.Transparency = 1
Title6.Text = ' <font color="rgb(255,0,255)">Sell</font> program setting'
Title6.TextColor3 = Color3.new(0.588235, 0, 1)
Title6.TextSize = 20
Title6.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Title6.TextScaled = true
Title6.TextWrapped = true
Title6.TextXAlignment = Enum.TextXAlignment.Left
Title6.RichText = true
Title6.Parent = SellSetting

local WaitSetting = Instance.new("Frame")
WaitSetting.Name = "WaitSetting"
WaitSetting.Position = UDim2.new(0.5, 0, 0.5, 0)
WaitSetting.Size = UDim2.new(0, 350, 0, 200)
WaitSetting.BackgroundColor3 = Color3.new(0.109804, 0.0745098, 0.133333)
WaitSetting.BorderSizePixel = 0
WaitSetting.BorderColor3 = Color3.new(0, 0, 0)
WaitSetting.Visible = false
WaitSetting.ZIndex = 102
WaitSetting.AnchorPoint = Vector2.new(0.5, 0.5)
WaitSetting.Parent = TDSHub

local LineX18 = Instance.new("Frame")
LineX18.Name = "LineX"
LineX18.Position = UDim2.new(0.5, 0, 0, 0)
LineX18.Size = UDim2.new(1, 0, 0.01, 0)
LineX18.BackgroundColor3 = Color3.new(1, 0, 1)
LineX18.BorderSizePixel = 0
LineX18.BorderColor3 = Color3.new(0, 0, 0)
LineX18.AnchorPoint = Vector2.new(0.5, 0.5)
LineX18.Parent = WaitSetting

local Title7 = Instance.new("TextLabel")
Title7.Name = "Title"
Title7.Position = UDim2.new(0.02, 0, 0.00571429, 0)
Title7.Size = UDim2.new(0, 150, 0, 40)
Title7.BackgroundColor3 = Color3.new(1, 1, 1)
Title7.BackgroundTransparency = 1
Title7.BorderSizePixel = 0
Title7.BorderColor3 = Color3.new(0, 0, 0)
Title7.Transparency = 1
Title7.Text = '<font color="rgb(255,0,255)">Wait</font> program setting'
Title7.TextColor3 = Color3.new(0.588235, 0, 1)
Title7.TextSize = 20
Title7.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Title7.TextScaled = true
Title7.TextWrapped = true
Title7.TextXAlignment = Enum.TextXAlignment.Left
Title7.RichText = true
Title7.Parent = WaitSetting

local SaveButton5 = Instance.new("TextButton")
SaveButton5.Name = "SaveButton"
SaveButton5.Position = UDim2.new(0.7, 0, 0.775, 0)
SaveButton5.Size = UDim2.new(0, 100, 0, 40)
SaveButton5.BackgroundColor3 = Color3.new(0, 0.862745, 0.388235)
SaveButton5.BorderSizePixel = 0
SaveButton5.BorderColor3 = Color3.new(0, 0, 0)
SaveButton5.Text = "Save"
SaveButton5.TextColor3 = Color3.new(1, 1, 1)
SaveButton5.TextSize = 30
SaveButton5.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
SaveButton5.TextWrapped = true
SaveButton5.Parent = WaitSetting

local UICorner23 = Instance.new("UICorner")
UICorner23.Name = "UICorner"
UICorner23.CornerRadius = UDim.new(0.15, 0)
UICorner23.Parent = SaveButton5

local CancelButton5 = Instance.new("TextButton")
CancelButton5.Name = "CancelButton"
CancelButton5.Position = UDim2.new(0.47, 0, 0.775, 0)
CancelButton5.Size = UDim2.new(0, 75, 0, 40)
CancelButton5.BackgroundColor3 = Color3.new(0.862745, 0.196078, 0.196078)
CancelButton5.BorderSizePixel = 0
CancelButton5.BorderColor3 = Color3.new(0, 0, 0)
CancelButton5.Text = "Cancel"
CancelButton5.TextColor3 = Color3.new(1, 1, 1)
CancelButton5.TextSize = 20
CancelButton5.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
CancelButton5.TextWrapped = true
CancelButton5.Parent = WaitSetting

local UICorner24 = Instance.new("UICorner")
UICorner24.Name = "UICorner"
UICorner24.CornerRadius = UDim.new(0.15, 0)
UICorner24.Parent = CancelButton5

local Value = Instance.new("TextBox")
Value.Name = "Value"
Value.Position = UDim2.new(0.75, 0, 0.575, 0)
Value.Size = UDim2.new(0, 150, 0, 30)
Value.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Value.BorderSizePixel = 0
Value.BorderColor3 = Color3.new(0, 0, 0)
Value.AnchorPoint = Vector2.new(0.5, 0.5)
Value.Text = ""
Value.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Value.TextSize = 14
Value.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Value.TextScaled = true
Value.TextWrapped = true
Value.PlaceholderText = "..."
Value.Parent = WaitSetting

local LineX19 = Instance.new("Frame")
LineX19.Name = "LineX"
LineX19.Position = UDim2.new(0.5, 0, 1, 0)
LineX19.Size = UDim2.new(1, 0, 0.01, 0)
LineX19.BackgroundColor3 = Color3.new(1, 0, 0.435294)
LineX19.BorderSizePixel = 0
LineX19.BorderColor3 = Color3.new(0, 0, 0)
LineX19.AnchorPoint = Vector2.new(0.5, 0.5)
LineX19.Parent = Value

local TitleValue = Instance.new("TextLabel")
TitleValue.Name = "TitleValue"
TitleValue.Position = UDim2.new(0.75, 0, 0.4, 0)
TitleValue.Size = UDim2.new(0, 150, 0, 30)
TitleValue.BackgroundColor3 = Color3.new(1, 1, 1)
TitleValue.BackgroundTransparency = 1
TitleValue.BorderSizePixel = 0
TitleValue.BorderColor3 = Color3.new(0, 0, 0)
TitleValue.AnchorPoint = Vector2.new(0.5, 0.5)
TitleValue.Transparency = 1
TitleValue.Text = "Value"
TitleValue.TextColor3 = Color3.new(1, 0, 1)
TitleValue.TextSize = 14
TitleValue.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleValue.TextScaled = true
TitleValue.TextWrapped = true
TitleValue.Parent = WaitSetting

local TitleMode = Instance.new("TextLabel")
TitleMode.Name = "TitleMode"
TitleMode.Position = UDim2.new(0.25, 0, 0.4, 0)
TitleMode.Size = UDim2.new(0, 150, 0, 30)
TitleMode.BackgroundColor3 = Color3.new(1, 1, 1)
TitleMode.BackgroundTransparency = 1
TitleMode.BorderSizePixel = 0
TitleMode.BorderColor3 = Color3.new(0, 0, 0)
TitleMode.AnchorPoint = Vector2.new(0.5, 0.5)
TitleMode.Transparency = 1
TitleMode.Text = "Mode"
TitleMode.TextColor3 = Color3.new(1, 0, 1)
TitleMode.TextSize = 14
TitleMode.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
TitleMode.TextScaled = true
TitleMode.TextWrapped = true
TitleMode.Parent = WaitSetting

local Mode = Instance.new("TextButton")
Mode.Name = "Mode"
Mode.Position = UDim2.new(0.25, 0, 0.575, 0)
Mode.Size = UDim2.new(0, 150, 0, 30)
Mode.BackgroundColor3 = Color3.new(0.0666667, 0.0470588, 0.0823529)
Mode.BorderSizePixel = 0
Mode.BorderColor3 = Color3.new(0, 0, 0)
Mode.AnchorPoint = Vector2.new(0.5, 0.5)
Mode.Text = "Second"
Mode.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
Mode.TextSize = 25
Mode.FontFace = Font.new("rbxassetid://12187371840", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Mode.Parent = WaitSetting

local ConsoleOutside = Instance.new("ScrollingFrame")
ConsoleOutside.Name = "ConsoleOutside"
ConsoleOutside.Position = UDim2.new(0.85, 0, 0.5, 0)
ConsoleOutside.Size = UDim2.new(0, 300, 0, 350)
ConsoleOutside.BackgroundColor3 = Color3.new(0.0627451, 0.0588235, 0.0705882)
ConsoleOutside.BackgroundTransparency = 1
ConsoleOutside.BorderSizePixel = 0
ConsoleOutside.BorderColor3 = Color3.new(0, 0, 0)
ConsoleOutside.Visible = false
ConsoleOutside.AnchorPoint = Vector2.new(0.5, 0.5)
ConsoleOutside.Transparency = 1
ConsoleOutside.Active = true
ConsoleOutside.CanvasSize = UDim2.new(0, 0, 0, 0)
ConsoleOutside.ScrollBarImageColor3 = Color3.new(1, 0, 1)
ConsoleOutside.ScrollBarImageTransparency = 0.75
ConsoleOutside.ScrollBarThickness = 5
ConsoleOutside.AutomaticCanvasSize = Enum.AutomaticSize.Y
ConsoleOutside.Parent = TDSHub

local OutputSample3 = Instance.new("TextLabel")
OutputSample3.Name = "OutputSample"
OutputSample3.Position = UDim2.new(0.025, 0, 0, 0)
OutputSample3.Size = UDim2.new(0.95, 0, 0, 20)
OutputSample3.BackgroundColor3 = Color3.new(1, 1, 1)
OutputSample3.BackgroundTransparency = 1
OutputSample3.BorderSizePixel = 0
OutputSample3.BorderColor3 = Color3.new(0, 0, 0)
OutputSample3.Visible = false
OutputSample3.Transparency = 1
OutputSample3.Text = "[System]: 1m1m1m1m1m1m1m1m1m1m1m"
OutputSample3.TextColor3 = Color3.new(0.705882, 0.588235, 0.705882)
OutputSample3.TextSize = 17
OutputSample3.TextStrokeTransparency = 0.5
OutputSample3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
OutputSample3.TextXAlignment = Enum.TextXAlignment.Left
OutputSample3.Parent = ConsoleOutside

local Frame = TDSHub
if not Frame then return end
task.spawn(function()
	while true do
		local allOk = true
		for _, obj in ipairs(Frame:GetDescendants()) do
			if obj:IsA("TextLabel")
			or obj:IsA("TextBox")
			or obj:IsA("TextButton") then
				if obj.TextTransparency ~= 0 then
					obj.TextTransparency = 0
					allOk = false
				end
			end
		end
		if allOk then break end
		task.wait(0.1)
	end
end)
